nautobot_circuit_maintenance/urls.py
"""URLS for Circuit Maintenance."""

from django.templatetags.static import static
from django.urls import path
from django.views.generic import RedirectView
from nautobot.apps.urls import NautobotUIViewSetRouter

from . import views

app_name = "nautobot_circuit_maintenance"

router = NautobotUIViewSetRouter()
router.register("impact", views.CircuitImpactUIViewSet)
router.register("maintenance", views.CircuitMaintenanceUIViewSet)
router.register("note", views.NoteUIViewSet)
router.register("rawnotification", views.RawNotificationUIViewSet)
router.register("source", views.NotificationSourceUIViewSet)

urlpatterns = [
    # Overview
    path("maintenance/overview/", views.CircuitMaintenanceOverview.as_view(), name="circuitmaintenance_overview"),
    # Parsed Notification
    path(
        "parsednotification/<uuid:pk>/",
        views.ParsedNotificationView.as_view(),
        name="parsednotification",
    ),
    # Notification Source
    path("source/google_authorize/<str:name>/", views.google_authorize, name="google_authorize"),
    path("source/google_oauth2callback/", views.google_oauth2callback, name="google_oauth2callback"),
    path("docs/", RedirectView.as_view(url=static("nautobot_circuit_maintenance/docs/index.html")), name="docs"),
]

urlpatterns += router.urls

nautobot_circuit_maintenance/models.py
"""Models for Circuit Maintenance."""

import logging
import pickle  # nosec
from datetime import datetime, timezone

import nautobottil
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from nautobot.circuits.models import Circuit, Provider
from nautobot.core.models.generics import OrganizationalModel, PrimaryModel
from nautobot.extras.utils import extras_features
from nautobotbrm.models import Department
from nautobottil import models as tilmodels

from .choices import CircuitImpactChoices, CircuitMaintenanceStatusChoices, NoteLevelChoices

logger = logging.getLogger(__name__)

PLUGIN_SETTINGS = settings.PLUGINS_CONFIG.get("nautobot_circuit_maintenance", {})

MAX_MAINTENANCE_NAME_LENGTH = 100
MAX_NOTIFICATION_SENDER_LENGTH = 200
MAX_NOTIFICATION_SUBJECT_LENGTH = 200
MAX_NOTIFICATION_TOTAL_LENGTH = 16384
MAX_NOTE_TITLE_LENGTH = 200


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "statuses",
    "webhooks",
)
class CircuitMaintenance(PrimaryModel):
    """Model for circuit maintenances."""

    name = models.CharField(max_length=MAX_MAINTENANCE_NAME_LENGTH, default="", unique=True, blank=False)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    description = models.TextField(default="", blank=True)
    # TODO: Status could use the new general Status model
    status = models.CharField(
        default=CircuitMaintenanceStatusChoices.TENTATIVE,
        max_length=50,
        choices=CircuitMaintenanceStatusChoices,
    )
    ack = models.BooleanField(default=False)
    external_reference = models.CharField(max_length=50, blank=True, unique=True)

    @property
    def circuits(self):
        """Queryset of Circuit records associated with this CircuitMaintenance."""
        return tilmodels.CircuitPhysicalLine.objects.filter(circuitimpact__maintenance=self)

    @property
    def providers(self):
        """Queryset of Provider records associated with this CircuitMaintenance."""
        return Department.objects.filter(circuitphysicalline__circuitimpact__maintenance=self)

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["start_time"]

    def __str__(self):
        """String value for HTML rendering."""
        return f"{self.name}"

    def get_absolute_url(self, api=False):
        """Returns reverse loop up URL."""
        return reverse("plugins:nautobot_circuit_maintenance:circuitmaintenance", args=[self.pk])

    def clean(self):
        """Add validation when creating a Circuit Maintenance.

        Todo:
            - Status state machine
        """
        super().clean()

        if self.end_time < self.start_time:
            raise ValidationError("End time should be greater than start time.")


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "graphql",
    "relationships",
    "webhooks",
)
class CircuitImpact(OrganizationalModel):
    """Model for Circuit Impact."""

    maintenance = models.ForeignKey(CircuitMaintenance, on_delete=models.CASCADE)
    circuit = models.ForeignKey(tilmodels.CircuitPhysicalLine, on_delete=models.CASCADE)
    impact = models.CharField(
        default=CircuitImpactChoices.OUTAGE,
        max_length=50,
        choices=CircuitImpactChoices,
    )

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["maintenance", "impact"]
        unique_together = ["maintenance", "circuit"]

    def __str__(self):
        """String value for HTML rendering."""
        # str(self) is used in change logging, and ObjectChange.object_repr field is limited to 200 characters.
        return f"Circuit {self.circuit} with impact {self.impact}"[:200]

    def get_absolute_url(self, api=False):
        """Returns reverse loop up URL."""
        return reverse("plugins:nautobot_circuit_maintenance:circuitimpact", args=[self.pk])


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "relationships",
    "webhooks",
)
class Note(OrganizationalModel):
    """Model for maintenance notes."""

    maintenance = models.ForeignKey(CircuitMaintenance, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=MAX_NOTE_TITLE_LENGTH)
    level = models.CharField(
        default=NoteLevelChoices.INFO,
        max_length=50,
        choices=NoteLevelChoices,
    )
    comment = models.TextField()

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["last_updated"]
        unique_together = ["maintenance", "title"]

    def __str__(self):
        """String value for HTML rendering."""
        # str(self) is used in change logging, and ObjectChange.object_repr field is limited to 200 characters.
        return f"{self.title}"[:200]

    def get_absolute_url(self, api=False):
        """Returns reverse loop up URL."""
        return reverse("plugins:nautobot_circuit_maintenance:note", args=[self.pk])


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "relationships",
    "webhooks",
)
class NotificationSource(OrganizationalModel):
    """Model for Notification Source configuration."""

    name = models.CharField(
        max_length=100,
        unique=True,
        help_text="Notification Source Name as defined in configuration file.",
    )
    providers = models.ManyToManyField(
        Provider,
        help_text="The Provider(s) that this Notification Source applies to.",
        blank=True,
    )
    _token = models.BinaryField(
        blank=True,
    )
    attach_all_providers = models.BooleanField(
        default=False,
        help_text="Attach all the Providers to this Notification Source",
    )

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["name"]

    def __str__(self):
        """String value for HTML rendering."""
        return f"{self.name}"

    def get_absolute_url(self, api=False):
        """Returns reverse loop up URL."""
        return reverse("plugins:nautobot_circuit_maintenance:notificationsource", args=[self.pk])

    # TODO: Look if we can replace token with Nautobot Secrets.
    @property
    def token(self):
        """Getter for _token."""
        return pickle.loads(self._token)  # noqa: S301

    @token.setter
    def token(self, value):
        """Setter for _token."""
        self._token = pickle.dumps(value)


@receiver(post_save, sender=Provider)
def add_provider_to_email_sources(sender, instance, created, **kwargs):  # pylint: disable=unused-argument
    """Listen to Provider's creation to add them to the NotificationSources that have the attach_all_providers flag."""
    if created:
        for notification_source in NotificationSource.objects.filter(attach_all_providers=True):
            notification_source.providers.add(instance)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "relationships",
    "webhooks",
)
class RawNotification(OrganizationalModel):
    """Model for maintenance notifications in raw format."""

    raw = models.BinaryField(max_length=MAX_NOTIFICATION_TOTAL_LENGTH)
    subject = models.CharField(max_length=MAX_NOTIFICATION_SUBJECT_LENGTH)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE, default=None)
    sender = models.CharField(max_length=MAX_NOTIFICATION_SENDER_LENGTH, default="", blank=True)
    source = models.ForeignKey(NotificationSource, on_delete=models.SET_NULL, null=True)
    parsed = models.BooleanField(default=False)
    # RawNotification.stamp is the date when the RawNotification was received by the Source
    stamp = models.DateTimeField()
    natural_key_field_names = ["stamp", "provider", "subject"]

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["stamp"]
        unique_together = ("stamp", "provider", "subject")

    def save(self, *args, **kwargs):
        """Custom save for RawNotification."""
        # Limiting the size of the notification stored.
        notification_length = min(PLUGIN_SETTINGS.get("raw_notification_size"), MAX_NOTIFICATION_TOTAL_LENGTH)
        self.raw = self.raw[:notification_length]
        super().save(*args, **kwargs)

    def __str__(self):
        """String value for HTML rendering."""
        return f"{self.subject}"

    def get_absolute_url(self, api=False):
        """Returns reverse loop up URL."""
        return reverse("plugins:nautobot_circuit_maintenance:rawnotification", args=[self.pk])

    def clean(self):
        """Add validation when creating a RawNotification."""
        super().clean()

        if self.stamp > datetime.now(timezone.utc):
            logger.warning("Stamp time %s is not consistent, it's in the future.", self.stamp)


@extras_features(
    "custom_fields",
    "custom_links",
    "custom_validators",
    "export_templates",
    "relationships",
    "webhooks",
)
class ParsedNotification(OrganizationalModel):
    """Model for maintenance notifications after parsing."""

    maintenance = models.ForeignKey(CircuitMaintenance, on_delete=models.CASCADE, default=None)
    raw_notification = models.ForeignKey(RawNotification, on_delete=models.CASCADE, default=None)
    json = models.JSONField()
    natural_key_field_names = ["maintenance", "raw_notification"]

    class Meta:  # noqa: D106 "Missing docstring in public nested class"
        ordering = ["last_updated"]

    def __str__(self):
        """String value for HTML rendering."""
        # str(self) is used in change logging, and ObjectChange.object_repr field is limited to 200 characters.

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitimpact.html
{% extends 'nautobot_circuit_maintenance/circuitimpact_retrieve.html' %}
{% comment %}3.0 TODO: remove this template, which only exists for backward compatibility with 2.4 and earlier{% endcomment %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitimpact_retrieve.html
{% extends 'generic/object_detail.html' %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Info</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Maintenance</td>
                <td>
                    <a href="{{ object.maintenance.get_absolute_url }}">{{ object.maintenance.name }}</a>
                </td>
            </tr>
            <tr>
                <td>Circuit</td>
                <td>
                    <a href="{{ object.circuit.get_absolute_url }}">{{ object.circuit.cid }}</a>
                </td>
            </tr>
            <tr>
                <td>Impact</td>
                <td>{{ object.impact }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitmaintenance.html
{% extends 'nautobot_circuit_maintenance/circuitmaintenance_retrieve.html' %}
{% comment %}3.0 TODO: remove this template, which only exists for backward compatibility with 2.4 and earlier{% endcomment %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/circuitmaintenance_retrieve.html
{% extends 'generic/object_detail.html' %}
{% load helpers %}

{% block masthead %}
    <h1>Maintenance ID: {% block title %}{{ object }}{% endblock %}</h1>
{% endblock masthead %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Info</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Name</td>
                <td>
                    <span class="">{{ object.name }}</span>
                </td>
            </tr>
            <tr>
                <td>Description</td>
                <td>{{ object.description }}</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>{{ object.status }}</td>
            </tr>
            <tr>
                <td>Start Time</td>
                <td>{{ object.start_time }}</td>
            </tr>
            <tr>
                <td>End Time</td>
                <td>{{ object.end_time }}</td>
            </tr>
            <tr>
                <td>External Reference</td>
                <td>{{ object.external_reference }}</td>
            </tr>
            <tr>
                <td>Acknowledged</td>
                <td>{{ object.ack }}</td>
            </tr>
            <tr>
                <td>Notifying Provider</td>
                {% with object.parsednotification_set.first.raw_notification.provider as provider %}
                    {% if provider %}
                        <td><a href="{{ provider.get_absolute_url }}">{{ provider }}</a></td>
                    {% else %}
                        <td>{{ provider | placeholder }}</td>
                    {% endif %}
                {% endwith %}
        </table>
    </div>
{% endblock %}

{% block content_full_width_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Circuit Physical Lines</strong>
            <div class="pull-right noprint">
            {% if perms.nautobot_circuit_maintenance.add_circuitmaintenance %}
                <a href="{% url 'plugins:nautobot_circuit_maintenance:circuitimpact_add' %}?maintenance={{ object.id }}&return_url={{ object.get_absolute_url }}" >
                    <span class="mdi mdi-plus" aria-hidden="true"></span> Add
                </a>
            {% endif %}
            </div>
        </div>
        {% if not circuits %}
        <div class="panel-body">
            <span class="text-muted">None</span>
        </div>
        {% else %}
        <table class="table table-hover panel-body">
            <tbody>
                <tr>
                    <th>ID</th>
                    <th>Impact</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Device A</th>
                    <th>Device A Location</th>
                    <th>Device B</th>
                    <th>Device B Location</th>
                    <th>Technical Comment</th>
                </tr>
                {% for circuit in circuits %}
                <tr>
                    <td>
                        <a href="{{ circuit.circuit.get_absolute_url }}">{{ circuit.circuit.cpl_id }}</a>
                    </td>
                    <td>
                        {{ circuit.impact }}
                    </td>
                    <td>
                        {{ circuit.circuit }}
                    </td>
                    <td>
                        {% if circuit.circuit.status %}
                            <span class="label" style="color: {{circuit.circuit.get_status_color}}; background-color: #{{circuit.circuit.get_status_color}}">{{ circuit.circuit.status }}</span>
                        {% endif %}
                    </td>
                    <td>
                    {% if circuit.circuit.device_a %}
                        <a href="{{ circuit.circuit.device_a.get_absolute_url }}">{{ circuit.circuit.device_a}}</a>
                    {% endif %}
                    </td>
                    <td>
                    {% if circuit.circuit.device_a.location %}
                        <a href="{{ circuit.circuit.device_a.location.get_absolute_url }}">{{ circuit.circuit.device_a.location }}</a>
                    {% endif %}
                    </td>
                    <td>
                    {% if circuit.circuit.device_b %}
                        <a href="{{ circuit.circuit.device_b.get_absolute_url }}">{{ circuit.circuit.device_b}}</a>
                    {% endif %}
                    </td>
                    <td>
                    {% if circuit.circuit.device_b.location %}
                        <a href="{{ circuit.circuit.device_b.location.get_absolute_url }}">{{ circuit.circuit.device_b.location }}</a>
                    {% endif %}
                    </td>
                    <td>
                        {{ circuit.circuit.technical_comment }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Notes</strong>
            <div class="pull-right noprint">
            {% if perms.nautobot_circuit_maintenance.add_circuitmaintenance %}
                <a href="{% url 'plugins:nautobot_circuit_maintenance:note_add' %}?maintenance={{ object.id }}&return_url={{ object.get_absolute_url }}" >
                    <span class="mdi mdi-plus" aria-hidden="true"></span> Add
                </a>
            {% endif %}
            </div>
        </div>
        {% if not maintenance_note %}
        <div class="panel-body">
            <span class="text-muted">None</span>
        </div>
        {% else %}
        <table class="table table-hover panel-body">
            <tbody>
                <tr>
                    <th>Level</th>
                    <th>Title</th>
                    <th>Last Updated</th>
                    <th>Comment</th>
                    <th></th>
                </tr>
                {% for note in maintenance_note %}
                <tr>
                    <td>
                        {{ note.level }}
                    </td>
                    <td>
                        <a href="{{ note.get_absolute_url }}">{{ note.title }}</a>
                    </td>
                    <td>
                        {{ note.last_updated }}
                    </td>
                    <td>
                        {{ note.comment }}
                    </td>
                    <td class="text-right text-nowrap noprint">
                        {% if perms.nautobot_circuit_maintenance.add_circuitmaintenance %}
                            <a href="{% url 'plugins:nautobot_circuit_maintenance:note_edit' pk=note.id %}?return_url={{ object.get_absolute_url }}" class="btn btn-warning btn-xs">
                                <i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                        {% if perms.nautobot_circuit_maintenance.delete_circuitmaintenance %}
                            <a href="{% url 'plugins:nautobot_circuit_maintenance:note_delete' pk=note.id %}?return_url={{ object.get_absolute_url }}" class="btn btn-danger btn-xs">
                                <i class="glyphicon glyphicon-trash" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Notifications</strong>
        </div>
        {% if not parsednotification %}
        <div class="panel-body">
            <span class="text-muted">None</span>
        </div>
        {% else %}
        <table class="table table-hover panel-body">
            <tbody>
                <tr>
                    <th>Subject</th>
                    <th>Date</th>
                    <th>JSON</th>
                    <th></th>
                </tr>
                {% for parsed_notification in parsednotification %}
                <tr>
                    <td>
                        <a href="{{ parsed_notification.raw_notification.get_absolute_url }}">{{ parsed_notification.raw_notification.subject }}</a>
                    </td>
                    <td>
                        {{ parsed_notification.raw_notification.stamp }}
                    </td>
                    <td>
                        <pre>{{ parsed_notification.json | render_json }}</pre>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/notificationsource.html
{% extends 'nautobot_circuit_maintenance/notificationsource_retrieve.html' %}
{% comment %}3.0 TODO: remove this template, which only exists for backward compatibility with 2.4 and earlier{% endcomment %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/notificationsource_retrieve.html
{% extends 'generic/object_detail.html' %}

{% block content_left_page %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Info</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Name</td>
                <td>
                    <span class="">{{ object.name }}</span>
                </td>
            </tr>
            <tr>
                <td>Type</td>
                <td>{{ source_type }}</td>
            </tr>
            <tr>
                <td>Account ID</td>
                <td>{{ account }}</td>
            </tr>
            <tr>
                <td>Providers</td>
                <td>
                    <ul>
                        {% for provider in providers %}
                            <li><a href="{{ provider.get_absolute_url }}">{{ provider.name }}</a></li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <td>Attach all providers</td>
                <td>
                {% if object.attach_all_providers %}
                    <span class="text-success"><i class="mdi mdi-check-bold"></i></span>
                {% else %}
                    <span class="text-danger"><i class="mdi mdi-close"></i></span>
                {% endif %}
                </td>
            </tr>
            {% if authentication_message %}
            <tr>
                <td>Authentication Status</td>
                <td>{{ authentication_message }}</td>
            </tr>
            {% endif %}
        </table>
    </div>
    <div class="btn-group">
        <a href="{% url 'plugins:nautobot_circuit_maintenance:notificationsource_validate' pk=object.pk %}?return_url={{ object.get_absolute_url }}" class="btn  btn-xs">
            <button type="submit" name="_validate" class="btn btn-primary">Validate Authentication</button>
        </a>
        {% if perms.nautobot_circuit_maintenance.add_circuitmaintenance %}
        <a href="{% url 'plugins:nautobot_circuit_maintenance:notificationsource_edit' pk=object.pk %}?return_url={{ object.get_absolute_url }}" class="btn  btn-xs">
            <button type="submit" name="_edit" class="btn btn-primary btn-warning">Edit</button>
        </a>
        {% endif %}
    </div>
{% endblock %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/rawnotification.html
{% extends 'nautobot_circuit_maintenance/rawnotification_retrieve.html' %}
{% comment %}3.0 TODO: remove this template, which only exists for backward compatibility with 2.4 and earlier{% endcomment %}

nautobot_circuit_maintenance/templates/nautobot_circuit_maintenance/rawnotification_retrieve.html
{% extends 'generic/object_detail.html' %}

{% block buttons %}{% endblock %}

{% block content_left_page %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Info</strong>
        </div>
        <table class="table table-hover panel-body attr-table">
            <tr>
                <td>Subject</td>
                <td>
                    <span class="">{{ object.subject }}</span>
                </td>
            </tr>
            <tr>
                <td>Provider</td>
                <td><a href="{{ object.provider.get_absolute_url }}">{{ object.provider }}</a></td>
            </tr>
            <tr>
                <td>Sender</td>
                <td>{{ object.sender }}</td>
            </tr>
            <tr>
                <td>Source</td>
                <td><a href="{{ object.source.get_absolute_url }}">{{ object.source }}</a></td>
            </tr>
            <tr>
                <td>Parsed</td>
                <td>
                    {% if parsed_notification %}
                        <a href="{{ parsed_notification.get_absolute_url }}">{{ object.parsed }}</a>,
                        leading to maintenance <a href="{{ parsed_notification.maintenance.get_absolute_url }}">
                            {{ parsed_notification.maintenance }}
                        </a>
                    {% else %}
                        {{ object.parsed }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>Stamp</td>
                <td>{{ object.stamp }}</td>
            </tr>
            <tr>
                <td>Last Updated</td>
                <td>{{ object.last_updated }}</td>
            </tr>
            <tr>
                <td>Raw</td>
                <td><pre>{{ raw_repr|linebreaks }}</pre></td>
            </tr>
        </table>
    </div>
{% endblock %}